#!/bin/bash

export DB_URL
while goose -env db down; do
  sleep 0.1
done

goose -env db up
if [ $? -ne 0 ]; then
  exit 1
fi

mkdir -p cover
# coverage ignores test use from other packages, but that's OK
go test -covermode=count -coverprofile=cover/core.cover    ./core && \
go test -covermode=count -coverprofile=cover/gateway.cover ./gateway && \
go test -covermode=count -coverprofile=cover/server.cover  ./server

if [ $? -ne 0 ]; then
  exit 1
fi

echo "mode: count">all.cover
grep -h -v "mode: count" cover/*.cover >> all.cover

if [ "CI" != ""  ]; then
  exit 0
fi

go tool cover -func=all.cover|sort -rnk 3|sed 's/.*\/ibconnect\///g'|sed 's/\t/ /g'
go tool cover -html=all.cover
